"use client";

import { useQuery } from "@tanstack/react-query";
import { BookOpen, Database, Link2, ShieldCheck } from "lucide-react";
import { api } from "@/lib/api";
import { Badge, Card } from "@/components/ui";
import { PageHeading } from "@/components/page-heading";

type Catalog={metrics:{name:string;label:string;description:string;kind:string;entity:string;format:string;valid_dimensions:string[]}[];dimensions:{name:string;label:string;table:string;column:string}[];tables:{name:string;description:string;primary_key:string;foreign_keys:Record<string,string>;columns:string[];pii_columns:string[]}[]};
export function CatalogPage({view}:{view:"metrics"|"tables"}){const query=useQuery({queryKey:["catalog"],queryFn:()=>api<Catalog>("/catalog")});return <><PageHeading eyebrow="Semantic layer" title={view==="metrics"?"Metrics catalog":"Data catalog"} description={view==="metrics"?"The governed business definitions Copilot must resolve before generating SQL.":"Machine-readable schema context exposed selectively to the analytics planner."}/>{query.isLoading&&<div className="grid gap-4 lg:grid-cols-2"><div className="skeleton h-60"/><div className="skeleton h-60"/></div>}{query.isError&&<Card className="p-6"><Badge tone="warning">Catalog unavailable</Badge><p className="mt-3 text-sm text-[#747b8b]">{query.error.message}</p></Card>}{query.data&&view==="metrics"&&<div className="grid gap-4 lg:grid-cols-2">{query.data.metrics.map(metric=><Card key={metric.name} className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#f0efff] text-[#635bff]"><BookOpen size={17}/></div><div><h2 className="font-bold">{metric.label}</h2><code className="text-[11px] text-[#838a99]">{metric.name}</code></div></div><Badge tone="accent">{metric.format}</Badge></div><p className="mt-4 text-sm leading-6 text-[#697080]">{metric.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{metric.valid_dimensions.map(item=><Badge key={item}>{item.replaceAll("_"," ")}</Badge>)}</div><div className="mt-4 border-t border-[#eceef2] pt-3 text-xs text-[#858c9b]">Entity: <span className="font-semibold text-[#545b6a]">{metric.entity}</span> · Type: <span className="font-semibold text-[#545b6a]">{metric.kind}</span></div></Card>)}</div>}{query.data&&view==="tables"&&<div className="grid gap-4 lg:grid-cols-2">{query.data.tables.map(table=><Card key={table.name} className="overflow-hidden"><div className="flex items-start justify-between border-b border-[#e8eaf0] p-5"><div className="flex gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#eaf7f2] text-[#16875d]"><Database size={17}/></div><div><h2 className="font-bold capitalize">{table.name}</h2><p className="mt-1 text-xs text-[#767d8d]">{table.description}</p></div></div><Badge tone="success"><ShieldCheck size={11} className="mr-1"/>No PII</Badge></div><div className="p-5"><div className="eyebrow">Columns</div><div className="mt-3 flex flex-wrap gap-2">{table.columns.map(column=><code key={column} className="rounded-md bg-[#f3f4f7] px-2 py-1 text-[11px] text-[#555d6d]">{column}{column===table.primary_key?" · PK":""}</code>)}</div>{Object.keys(table.foreign_keys).length>0&&<div className="mt-5"><div className="eyebrow">Relationships</div>{Object.entries(table.foreign_keys).map(([key,value])=><div key={key} className="mt-2 flex items-center gap-2 text-xs text-[#666e7e]"><Link2 size={13}/><code>{key}</code><span>→</span><code>{value}</code></div>)}</div>}</div></Card>)}</div>}</>}

