"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowUp, BrainCircuit, Search, Sparkles } from "lucide-react";
import { analyze, getHistoryItem, saveNotebookInsight } from "@/lib/api";
import type { AnalysisResponse, ClarificationResponse, ErrorResponse } from "@/lib/types";
import { Badge, Button, Card } from "@/components/ui";
import { PageHeading } from "@/components/page-heading";
import { CopilotResult } from "@/components/copilot-result";

const examples=["Why did checkout conversion fall last week?","Where are users dropping during onboarding?","Which acquisition channel converts best?","Which plan generates the most MRR?","Which features are associated with better retention?"];
const stages=["Understanding the question","Resolving governed metrics","Generating safe SQL","Validating the query","Analyzing product data","Investigating drivers","Preparing evidence"];

export function Copilot() {
  const params=useSearchParams(); const initial=params.get("question")??""; const initialQueryId=params.get("query_id"); const initialized=useRef<string|null>(null);
  const [question,setQuestion]=useState(initial); const [mode,setMode]=useState<"quick"|"deep">("deep"); const [result,setResult]=useState<AnalysisResponse|null>(null); const [clarification,setClarification]=useState<ClarificationResponse|null>(null); const [error,setError]=useState<ErrorResponse|null>(null); const [loading,setLoading]=useState(false); const [stage,setStage]=useState(0); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [saveError,setSaveError]=useState<string|null>(null);
  useEffect(()=>{const key=initialQueryId?`history:${initialQueryId}`:initial?`question:${initial}`:"";if(!key||initialized.current===key)return;initialized.current=key;if(initialQueryId) void reopen(initialQueryId); else void run(initial);},[initial,initialQueryId]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!loading)return;const timer=setInterval(()=>setStage((value)=>Math.min(value+1,stages.length-1)),700);return()=>clearInterval(timer);},[loading]);
  async function run(value=question,selectedMetric?:string){if(value.trim().length<3)return;setQuestion(value);setLoading(true);setStage(0);setError(null);setClarification(null);setSaved(false);setSaveError(null);try{const response=await analyze(value,mode,selectedMetric);if(response.type==="analysis"){setResult(response);}else if(response.type==="clarification"){setResult(null);setClarification(response);}else{setResult(null);setError(response);}}catch(caught){setResult(null);setError({type:"error",code:"API_UNAVAILABLE",message:caught instanceof Error?caught.message:"The analysis service is unavailable.",retryable:true});}finally{setLoading(false);}}
  async function reopen(queryId:string){setLoading(true);setStage(stages.length-1);setError(null);setClarification(null);setSaved(false);setSaveError(null);try{const response=await getHistoryItem(queryId);if(response.type==="analysis"){setMode(response.mode);setQuestion(response.question);setResult(response);}else if(response.type==="clarification"){setClarification(response);}else{setError(response);}}catch(caught){setError({type:"error",code:"HISTORY_UNAVAILABLE",message:caught instanceof Error?caught.message:"The saved analysis is unavailable.",retryable:false});}finally{setLoading(false);}}
  async function saveCurrent(){if(!result||saving||saved)return;setSaving(true);setSaveError(null);try{await saveNotebookInsight(result.metadata.query_id);setSaved(true);}catch(caught){setSaveError(caught instanceof Error?caught.message:"The notebook could not be updated.");}finally{setSaving(false);}}
  function submit(event:FormEvent){event.preventDefault();void run();}
  return <><PageHeading eyebrow="AI analytics copilot" title="Ask your product data" description="From a business question to a validated investigation—with governed definitions, deterministic calculations, and evidence you can inspect." action={<div className="flex rounded-lg border border-[#e1e5ec] bg-white p-1"><button onClick={()=>setMode("quick")} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${mode==="quick"?"bg-[#171a23] text-white":"text-[#697080]"}`}>Quick answer</button><button onClick={()=>setMode("deep")} className={`rounded-md px-3 py-1.5 text-xs font-semibold ${mode==="deep"?"bg-[#171a23] text-white":"text-[#697080]"}`}>Deep dive</button></div>}/>
    <Card className="p-3 shadow-[0_12px_40px_rgba(35,31,92,.06)]"><form onSubmit={submit} className="flex items-end gap-3"><div className="flex flex-1 items-start gap-3 px-2 py-2"><Search size={19} className="mt-1 text-[#8a91a0]"/><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask anything about your product data…" className="min-h-12 flex-1 resize-none border-0 bg-transparent py-1 text-sm leading-6 outline-none placeholder:text-[#a1a7b3]" aria-label="Product analytics question"/></div><Button type="submit" size="lg" disabled={loading||question.trim().length<3} aria-label="Run analysis"><ArrowUp size={18}/></Button></form></Card>
    {!result&&!loading&&!clarification&&!error&&<div className="mt-8"><div className="eyebrow mb-3">Try an investigation</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{examples.map((item,index)=><button key={item} onClick={()=>void run(item)} className="panel flex items-start gap-3 p-4 text-left transition-all hover:-translate-y-0.5 hover:border-[#ccc7fc] hover:shadow-md"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[#f2f0ff] text-[#635bff]"><Sparkles size={15}/></div><div><div className="text-sm font-semibold leading-5">{item}</div><div className="mt-2 text-[11px] text-[#8b92a1]">{index===0?"Diagnostic · comparison · drivers":"Governed product analysis"}</div></div></button>)}</div></div>}
    {loading&&<Card className="mt-7 p-6"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#eeecff] text-[#635bff]"><BrainCircuit size={21} className="animate-pulse"/></div><div className="flex-1"><div className="text-sm font-bold">{stages[stage]}</div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#edeff3]"><div className="h-full rounded-full bg-[#635bff] transition-all" style={{width:`${((stage+1)/stages.length)*100}%`}}/></div></div></div><div className="mt-6 grid gap-3 md:grid-cols-3"><div className="skeleton h-24"/><div className="skeleton h-24"/><div className="skeleton h-24"/></div></Card>}
    {clarification&&<Card className="mt-7 p-6"><Badge tone="warning">Clarification needed</Badge><h2 className="mt-3 text-lg font-bold">{clarification.reason}</h2><div className="mt-5 grid gap-3 md:grid-cols-2">{clarification.options.map(option=><button key={option.metric} onClick={()=>void run(question,option.metric)} className="rounded-xl border border-[#e2e5eb] p-4 text-left hover:border-[#c9c3fc] hover:bg-[#fbfaff]"><div className="font-semibold">{option.label}</div><p className="mt-1 text-xs leading-5 text-[#747b8b]">{option.definition}</p></button>)}</div></Card>}
    {error&&<Card className="mt-7 border-[#ffd8dc] bg-[#fffafb] p-6"><Badge tone="warning">{error.code.replaceAll("_"," ")}</Badge><h2 className="mt-3 text-lg font-bold">Analysis could not be completed</h2><p className="mt-2 text-sm text-[#707786]">{error.message}</p>{error.retryable&&<Button className="mt-5" variant="secondary" onClick={()=>void run()}>Try again</Button>}</Card>}
    {result&&<CopilotResult result={result} onFollowUp={(next)=>void run(next)} onSave={()=>void saveCurrent()} saved={saved} saving={saving} saveError={saveError}/>}</>;
}
