"use client";

import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Clock, History as HistoryIcon, Sparkles } from "lucide-react";
import { api, getSessionId } from "@/lib/api";
import { Badge, Button, Card } from "@/components/ui";
import { PageHeading } from "@/components/page-heading";

type HistoryItem={query_id:string;question:string;mode:string;intent:string;metric:string;provider:string;latency_ms:number;status:string;created_at:string};
export function HistoryPage(){const query=useQuery({queryKey:["history"],queryFn:()=>api<HistoryItem[]>("/history",{headers:{"X-ProductLens-Session":getSessionId()}})});return <><PageHeading eyebrow="Analysis history" title="Recent investigations" description="History is scoped to this anonymous browser session. Reopen the original evidence, SQL, and recommendations." action={<Button asChild><Link href="/copilot"><Sparkles size={15}/>New analysis</Link></Button>}/>{query.isLoading&&<div className="space-y-3"><div className="skeleton h-24"/><div className="skeleton h-24"/><div className="skeleton h-24"/></div>}{query.isError&&<Card className="p-6"><Badge tone="warning">History unavailable</Badge><p className="mt-3 text-sm text-[#747b8b]">{query.error.message}</p></Card>}{query.data?.length===0&&<Card className="grid min-h-80 place-items-center text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-[#f1f0ff] text-[#635bff]"><HistoryIcon size={20}/></div><h2 className="mt-4 font-bold">No analyses yet</h2><p className="mt-2 text-sm text-[#747b8b]">Questions you run in this browser will appear here.</p></div></Card>}{query.data&&query.data.length>0&&<Card className="overflow-hidden"><div className="divide-y divide-[#e8eaf0]">{query.data.map(item=><Link key={item.query_id} href={`/copilot?question=${encodeURIComponent(item.question)}`} className="flex flex-col justify-between gap-3 p-5 transition-colors hover:bg-[#fafaff] sm:flex-row sm:items-center"><div><div className="font-semibold">{item.question}</div><div className="mt-2 flex flex-wrap items-center gap-2"><Badge tone="accent">{item.mode}</Badge><Badge>{item.metric?.replaceAll("_"," ")}</Badge><span className="flex items-center gap-1 text-[11px] text-[#858c9b]"><Clock size={12}/>{new Date(item.created_at).toLocaleString()}</span></div></div><div className="text-right"><div className="text-xs font-semibold text-[#596071]">{item.provider}</div><div className="mt-1 text-[11px] text-[#9299a8]">{(item.latency_ms/1000).toFixed(2)}s</div></div></Link>)}</div></Card>}</>}

