"""Initial ProductLens schemas, tables, views, roles, and grants.

Revision ID: 0001_initial
"""

from __future__ import annotations

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


DDL = r"""
CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS operational;

DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'migration_owner') THEN
    CREATE ROLE migration_owner LOGIN NOINHERIT CREATEROLE;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_writer') THEN
    CREATE ROLE app_writer LOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'analytics_reader') THEN
    CREATE ROLE analytics_reader LOGIN;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS core.users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signup_at TIMESTAMPTZ NOT NULL,
  country TEXT NOT NULL,
  region TEXT NOT NULL,
  acquisition_channel TEXT NOT NULL,
  campaign TEXT NOT NULL,
  plan TEXT NOT NULL,
  company_size TEXT NOT NULL,
  signup_source TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS core.sessions (
  session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES core.users(user_id),
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ NOT NULL,
  device TEXT NOT NULL,
  browser TEXT NOT NULL,
  operating_system TEXT NOT NULL,
  channel TEXT NOT NULL,
  campaign TEXT NOT NULL,
  landing_page TEXT NOT NULL,
  CHECK (ended_at >= started_at)
);

CREATE TABLE IF NOT EXISTS core.events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES core.users(user_id),
  session_id BIGINT NOT NULL REFERENCES core.sessions(session_id),
  event_name TEXT NOT NULL,
  event_timestamp TIMESTAMPTZ NOT NULL,
  page TEXT NOT NULL,
  feature TEXT,
  properties JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS core.subscriptions (
  subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES core.users(user_id),
  plan TEXT NOT NULL,
  status TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  trial_started_at TIMESTAMPTZ,
  trial_ended_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  mrr NUMERIC(12,2) NOT NULL CHECK (mrr >= 0),
  billing_interval TEXT NOT NULL CHECK (billing_interval IN ('monthly', 'annual'))
);

CREATE TABLE IF NOT EXISTS core.transactions (
  transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES core.users(user_id),
  subscription_id BIGINT REFERENCES core.subscriptions(subscription_id),
  timestamp TIMESTAMPTZ NOT NULL,
  amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  status TEXT NOT NULL CHECK (status IN ('success', 'failed', 'refunded')),
  payment_method TEXT NOT NULL,
  transaction_type TEXT NOT NULL CHECK (transaction_type IN ('charge', 'renewal', 'refund')),
  failure_reason TEXT
);

CREATE TABLE IF NOT EXISTS operational.dataset_metadata (
  dataset_version TEXT PRIMARY KEY,
  dataset_as_of DATE NOT NULL,
  seed BIGINT NOT NULL,
  profile TEXT NOT NULL,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  row_counts JSONB NOT NULL,
  scenario_parameters JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS operational.query_history (
  query_id UUID PRIMARY KEY,
  session_hash CHAR(64) NOT NULL,
  question TEXT NOT NULL,
  mode TEXT NOT NULL,
  intent TEXT,
  metric TEXT,
  generated_sql TEXT,
  response JSONB,
  chart_spec JSONB,
  provider TEXT NOT NULL,
  latency_ms DOUBLE PRECISION,
  status TEXT NOT NULL,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS operational.query_audit (
  audit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  query_id UUID NOT NULL,
  session_hash CHAR(64),
  question TEXT,
  generated_sql TEXT,
  validation_status TEXT NOT NULL,
  execution_status TEXT,
  validation_errors JSONB NOT NULL DEFAULT '[]'::jsonb,
  execution_ms DOUBLE PRECISION,
  row_count INTEGER,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS operational.request_quota (
  quota_key CHAR(64) NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  window_kind TEXT NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (quota_key, window_start, window_kind)
);

CREATE TABLE IF NOT EXISTS operational.result_cache (
  cache_key CHAR(64) PRIMARY KEY,
  dataset_version TEXT NOT NULL,
  payload JSONB NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_signup ON core.users(signup_at);
CREATE INDEX IF NOT EXISTS idx_users_channel ON core.users(acquisition_channel);
CREATE INDEX IF NOT EXISTS idx_sessions_user_started ON core.sessions(user_id, started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON core.sessions(started_at);
CREATE INDEX IF NOT EXISTS idx_sessions_segments ON core.sessions(device, browser, channel);
CREATE INDEX IF NOT EXISTS idx_events_name_time ON core.events(event_name, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_events_user_time ON core.events(user_id, event_timestamp);
CREATE INDEX IF NOT EXISTS idx_events_session ON core.events(session_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_user ON core.subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_status_started ON core.subscriptions(status, started_at);
CREATE INDEX IF NOT EXISTS idx_transactions_time_status ON core.transactions(timestamp, status);
CREATE INDEX IF NOT EXISTS idx_transactions_user ON core.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_history_session_time ON operational.query_history(session_hash, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_query ON operational.query_audit(query_id);

CREATE OR REPLACE VIEW analytics.users AS SELECT * FROM core.users;
CREATE OR REPLACE VIEW analytics.sessions AS SELECT * FROM core.sessions;
CREATE OR REPLACE VIEW analytics.events AS SELECT * FROM core.events;
CREATE OR REPLACE VIEW analytics.subscriptions AS SELECT * FROM core.subscriptions;
CREATE OR REPLACE VIEW analytics.transactions AS SELECT * FROM core.transactions;

REVOKE ALL ON SCHEMA core, operational, analytics FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA core, operational, analytics FROM PUBLIC;

-- The migration owner is the only application role with schema/data-management
-- privileges. Runtime roles below are deliberately narrower.
GRANT ALL ON SCHEMA core, operational, analytics TO migration_owner;
GRANT ALL ON ALL TABLES IN SCHEMA core, operational, analytics TO migration_owner;
GRANT ALL ON ALL SEQUENCES IN SCHEMA core, operational, analytics TO migration_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA core, operational, analytics GRANT ALL ON TABLES TO migration_owner;
ALTER DEFAULT PRIVILEGES IN SCHEMA core, operational, analytics GRANT ALL ON SEQUENCES TO migration_owner;

GRANT USAGE ON SCHEMA analytics TO analytics_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO analytics_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO analytics_reader;
ALTER ROLE analytics_reader SET default_transaction_read_only = on;
ALTER ROLE analytics_reader SET statement_timeout = '5s';
ALTER ROLE analytics_reader SET search_path = analytics;

GRANT USAGE ON SCHEMA operational TO app_writer;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA operational TO app_writer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA operational TO app_writer;
GRANT USAGE ON SCHEMA analytics TO app_writer;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO app_writer;
"""


def upgrade() -> None:
    op.execute(DDL)


def downgrade() -> None:
    op.execute("DROP SCHEMA IF EXISTS operational CASCADE")
    op.execute("DROP SCHEMA IF EXISTS analytics CASCADE")
    op.execute("DROP SCHEMA IF EXISTS core CASCADE")
